// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTailnet(arg1:main.AddTailnetRequest):Promise<void>;

export function GetDashboard():Promise<main.Dashboard>;

export function GetSettings():Promise<main.Settings>;

export function GetTailnetDetail(arg1:string):Promise<main.TailnetDetail>;

export function RemoveTailnet(arg1:string):Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;
