// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTailnet(arg1) {
  return window['go']['main']['App']['AddTailnet'](arg1);
}

export function GetDashboard() {
  return window['go']['main']['App']['GetDashboard']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTailnetDetail(arg1) {
  return window['go']['main']['App']['GetTailnetDetail'](arg1);
}

export function RemoveTailnet(arg1) {
  return window['go']['main']['App']['RemoveTailnet'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
